# Generated by Django 5.2 on 2025-05-06 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Webempresa',
            new_name='Store',
        ),
    ]
