# Generated by Django 5.2 on 2025-05-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_webempresa_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
